### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by matrixko** [bitpeach/EarthLiveForMac#1]
Great work thanks a lot !

**Comment by bitpeach** [comment]
@matrixko 
Hi, dear friend. The reason that your programming errors appeared **MAY BE** that your cloudinary name has been not added. In the demo, my program code has no cloudinary name and you should sign up that website to replace the line 18th of the program code by your self-name.

In addition, you should be careful about 2 points when using that program.
(1)This program needs Pillow. So your python environment should import Pillow. If you have no Pillow of python, you can use "pip install Pillow" or install Pillow.

(2)This demo has two code sentences in lines of 92nd and 93rd. The function of these two sentences is to delete the picture generated by this program, such as the 4k-size combined pictures. The reason is to avoid too many appearing big-size pictures, which are the encumbrance of occupation in your os system when running that programs. However, if you do not mind that and want to save the big-size beautiful pictures, you can block these two programming sentences (line 92nd and 93rd) for making that function invalid.

If you are a programmer, you can add a function of self-starting-up with os system booting, which has been not in my programs. 
Thank you for your comment.

**Comment by matrixko** [comment]
Yes it worked thanks a lot for your help and your work, it's amazing! I love it
